/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DatosLiberadosRouteImport } from './routes/datos-liberados'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReleasedDownloadRouteImport } from './routes/api.released-download'
import { Route as ApiBlobUploadRouteImport } from './routes/api.blob-upload'

const DatosLiberadosRoute = DatosLiberadosRouteImport.update({
  id: '/datos-liberados',
  path: '/datos-liberados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasedDownloadRoute = ApiReleasedDownloadRouteImport.update({
  id: '/api/released-download',
  path: '/api/released-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobUploadRoute = ApiBlobUploadRouteImport.update({
  id: '/api/blob-upload',
  path: '/api/blob-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/datos-liberados': typeof DatosLiberadosRoute
  '/api/blob-upload': typeof ApiBlobUploadRoute
  '/api/released-download': typeof ApiReleasedDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/datos-liberados': typeof DatosLiberadosRoute
  '/api/blob-upload': typeof ApiBlobUploadRoute
  '/api/released-download': typeof ApiReleasedDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/datos-liberados': typeof DatosLiberadosRoute
  '/api/blob-upload': typeof ApiBlobUploadRoute
  '/api/released-download': typeof ApiReleasedDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/datos-liberados'
    | '/api/blob-upload'
    | '/api/released-download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/datos-liberados'
    | '/api/blob-upload'
    | '/api/released-download'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/datos-liberados'
    | '/api/blob-upload'
    | '/api/released-download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DatosLiberadosRoute: typeof DatosLiberadosRoute
  ApiBlobUploadRoute: typeof ApiBlobUploadRoute
  ApiReleasedDownloadRoute: typeof ApiReleasedDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/datos-liberados': {
      id: '/datos-liberados'
      path: '/datos-liberados'
      fullPath: '/datos-liberados'
      preLoaderRoute: typeof DatosLiberadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/released-download': {
      id: '/api/released-download'
      path: '/api/released-download'
      fullPath: '/api/released-download'
      preLoaderRoute: typeof ApiReleasedDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob-upload': {
      id: '/api/blob-upload'
      path: '/api/blob-upload'
      fullPath: '/api/blob-upload'
      preLoaderRoute: typeof ApiBlobUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DatosLiberadosRoute: DatosLiberadosRoute,
  ApiBlobUploadRoute: ApiBlobUploadRoute,
  ApiReleasedDownloadRoute: ApiReleasedDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
